### PR TITLE
Devops 0000 temp

### PR DESCRIPTION
**Pull request by Hogue3pi**
Merging in some fixes for rds_local, rds_tunnel, utils.bash, to fix RDS tunnel creation.

### CODE REVIEW

**Comment by gangofnuns** [comment]
Hey Andy --

I did look through these  changes and they make sense.   We should take
some time to test them, though.

My environment is polluted at present, due to container work.   Can you do
the honors?  Once the code
is known to be working end-to-end, I am happy to merge.


Cheers --

**Comment by Hogue3pi** [comment]
Absolutely!  I did a battery of tests on this before I submitted the PR.  RDS tunneling is working as expected - apart from the known issue that the rds alias is broken.  Running rds_local directly works smoothly.  I'll be fixing the alias issue next in https://qventus.atlassian.net/browse/DEVOPS-7935.

**Comment by gangofnuns** [comment]
Awesome -- thank you.    I had a bit of a problem this weekend
which distracted me from getting a lot done on the containers.

I was targeted by a group of scammers working on BandLabs.com
and SoundCloud.  They didn't succeed in compromising any of my hosts,
but it pissed me off a little, enough to want to shut them down.  They'd
been working those communities for some time, giving young musicians
the false hope that they had been 'noticed' by agents from Sony
Entertainment,
and would soon be signed -- all they have to do is fill out this bogus
online form
with some trivial personal data.  Then the scammers would clean them out.

I ran a reflected XSS scanner against their online form, found a few vulns,
injected
some code, found their IP address, then reported it to the legal team at
Sony Music,
bandlabs, soundcloud, and the FBI, along with the history of where the
group had
been operating over the past few months, and the personal data I was able
to pull
from the form's version history.

Trying to catch up first thing this morning....

**Review by gangofnuns — APPROVED** [review]
LGTM.

**Pull request merged**
